-d C:\Users\zh\Desktop\Project_ZH\9.GW2A-LC-LogicsPI\2.Soft\3.KEY\Pro\impl\gwsynthesis\Pro.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\zh\Desktop\Project_ZH\9.GW2A-LC-LogicsPI\2.Soft\3.KEY\Pro\src\Pro.cst
-cfg C:\Users\zh\Desktop\Project_ZH\9.GW2A-LC-LogicsPI\2.Soft\3.KEY\Pro\impl\pnr\device.cfg
-sdc C:\Users\zh\Desktop\Project_ZH\9.GW2A-LC-LogicsPI\2.Soft\3.KEY\Pro\src\Pro.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
